version: "3"
services:
    backend:
        container_name: studiz-backend
        build: .
        # image: ghcr.io/studiz/studiz-backend:dev
        restart: on-failure
        ports:
        - "80:80"
networks:
    backend:
        external: true