name: studiz-backend-dev

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          push: true
          tags: ghcr.io/studiz/studiz-backend:dev

      - name: Copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ./docker-compose.dev.yml, ./nginx.conf, ./reverse-poxy.conf
          target: ~/studiz-backend/dev/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull images and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            docker rmi -f ghcr.io/studiz/studiz-backend:dev
            docker pull ghcr.io/studiz/studiz-backend:dev
            docker rm -f studiz-backend
            docker run -d --name studiz-backend -p 9091:9091 ghcr.io/studiz/studiz-backend:dev 
            docker-compose -f ~/studiz-backend/dev/docker-compose.dev.yml up -d